import Erdos364.DicksonLucas.ShiftedSquarePropagation

/-!
# Paper I theorem and axiom audit

This file is an evidence-only audit surface.  It changes no theorem and is
compiled by the Paper I reproduction gate.
-/

#check Erdos364.no_sm2LucasReal_seventeen_square_of_mod_eight_two
#check Erdos364.noSm2OuterSeventeenBlocks
#check Erdos364.ss41_shiftedSquare_impossible
#check Erdos364.no_outerLarge_selected_fortyOne
#check Erdos364.no_rankDefect_selected_fortyOne
#check Erdos364.sm2LucasReal_mod_four_two_of_odd
#check Erdos364.sm2LucasReal_mod_eight_six_of_index_mod_four_one
#check Erdos364.no_sm2LucasReal_seventeen_square_of_mod_four_two
#check Erdos364.no_sm2LucasReal_fortyOne_square_of_mod_four_two
#check Erdos364.sm2LucasReal_mul_of_odd_right
#check Erdos364.no_sm2LucasReal_shiftedSquare_of_odd_index_factor
#check Erdos364.normNegativeOneUnit_real_ne_square_add_one_of_index_factor
#check Erdos364.sm2LucasReal_sub_one_padicVal_two_of_positive_even
#check Erdos364.no_sm2LucasReal_shiftedSquare_of_positive_even_index
#check Erdos364.no_sm2LucasReal_shiftedSquare_of_positive_index_factor
#check Erdos364.normNegativeOneUnit_real_ne_square_add_one_of_positive_even_index
#check Erdos364.normNegativeOneUnit_real_ne_square_add_one_of_positive_index_factor

#print axioms Erdos364.no_sm2LucasReal_seventeen_square_of_mod_eight_two
#print axioms Erdos364.noSm2OuterSeventeenBlocks
#print axioms Erdos364.ss41_shiftedSquare_impossible
#print axioms Erdos364.no_outerLarge_selected_fortyOne
#print axioms Erdos364.no_rankDefect_selected_fortyOne
#print axioms Erdos364.sm2LucasReal_mod_four_two_of_odd
#print axioms Erdos364.sm2LucasReal_mod_eight_six_of_index_mod_four_one
#print axioms Erdos364.no_sm2LucasReal_seventeen_square_of_mod_four_two
#print axioms Erdos364.no_sm2LucasReal_fortyOne_square_of_mod_four_two
#print axioms Erdos364.sm2LucasReal_mul_of_odd_right
#print axioms Erdos364.no_sm2LucasReal_shiftedSquare_of_odd_index_factor
#print axioms Erdos364.normNegativeOneUnit_real_ne_square_add_one_of_index_factor
#print axioms Erdos364.sm2LucasReal_sub_one_padicVal_two_of_positive_even
#print axioms Erdos364.no_sm2LucasReal_shiftedSquare_of_positive_even_index
#print axioms Erdos364.no_sm2LucasReal_shiftedSquare_of_positive_index_factor
#print axioms Erdos364.normNegativeOneUnit_real_ne_square_add_one_of_positive_even_index
#print axioms Erdos364.normNegativeOneUnit_real_ne_square_add_one_of_positive_index_factor

-- Load-bearing source and terminology supports.
#print axioms Erdos364.sm2UpperNegativeUnit_pow_re
#print axioms Erdos364.Sm2LowerSquareUpperSourceGenerator.root_real_mod_eight
#print axioms Erdos364.sm2LowerSquareSource_iff_exists_generatorResidual
#print axioms Erdos364.pellRank_dvd_kernel
